exclude: "^docs/|/migrations/|/.vscode/|[^/]*.yaml$"
default_stages: [pre-commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: ["--config=setup.cfg"]
    additional_dependencies: [flake8-isort]

- repo: https://github.com/google/yapf
  rev: v0.40.1
  hooks:
  - id: yapf
    args: ["--recursive", "--parallel", "--diff"]
    files: ^app/
    additional_dependencies: ["toml"]
