apiVersion: v1
kind: Secret
metadata:
  name: sukimise-secret
type: Opaque
stringData:
  POSTGRES_DB: sukimise
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "1"
