# Generated by Django 5.2 on 2025-04-07 05:26

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension()
    ]
