# Generated by Django 5.2 on 2025-04-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='brand_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='collection_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='supplier_gin_idx',
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_name', 'brand_description'], name='brand_name_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['collection_name', 'collection_description'], name='collection_name_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name', 'product_description'], name='product_name_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_name', 'supplier_description'], name='supplier_name_desc_idx'),
        ),
    ]
