# Generated by Django 5.2 on 2025-04-07 06:17

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_brand_brand_name_desc_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand', index=django.contrib.postgres.indexes.GinIndex(
                fields=['brand_name', 'brand_description'],
                name='brand_name_gin_idx'),),
        migrations.AddIndex(
            model_name='collection', index=django.contrib.postgres.indexes.GinIndex(
                fields=['collection_name', 'collection_description'],
                name='collection_name_gin_idx'),),
        migrations.AddIndex(
            model_name='product', index=django.contrib.postgres.indexes.GinIndex(
                fields=['product_name', 'product_description'],
                name='product_name_gin_idx'),),
        migrations.AddIndex(
            model_name='supplier', index=django.contrib.postgres.indexes.GinIndex(
                fields=['supplier_name', 'supplier_description'],
                name='supplier_name_gin_idx'),),]
