# Generated by Django 5.2 on 2025-04-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_brand_brand_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'default_manager_name': 'all_objects', 'ordering': ['collection_id', 'collection_name'], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_manager_name': 'all_objects', 'ordering': ['product_id', 'product_name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'default_manager_name': 'all_objects', 'ordering': ['supplier_id', 'supplier_name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_description',
            field=models.CharField(max_length=512),
        ),
    ]
