# Generated by Django 5.2 on 2025-04-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_collection_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'default_manager_name': 'all_objects', 'ordering': ['brand_id', 'brand_name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_description',
            field=models.CharField(max_length=256),
        ),
    ]
